// <auto-generated />
namespace T1809E_Project_Sem3.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Add_seeding_product : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Add_seeding_product));
        
        string IMigrationMetadata.Id
        {
            get { return "202006020614083_Add_seeding_product"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
